### ISSUE TITLE
Help creating image

### ISSUE THREAD

**Issue by vididuc** [uros76/Controllino-with-Homeassistant#2]
Hello uros76
I live near Bern (Switzerland). I'm a German speaking guy. My controllino hotspot provider told me about this project.
I ran into an issue with my controllino hotspot.
The sd card seems to be defect. Therefore the controllino is not botting up anymore.
I'm searching an image file of the controllino hotsport software, that I could write on a new sd-card and bring the hotspot controllino back to life.
As I understood from your project. If I provide you the needed information you could create the image-file, right?
Is there a chance that we could give it a try? Of course I will pay for your work, just tell me how much.

Regards,
Marcos

**Comment by uros76** [comment]
Join the unofficial controllino users discord server here: https://discord.io/controllino

There's plenty of knowledge and guides shared, including how to get the image.
